#############################################################################
# Makefile for building: release/Pencil
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Mar 11 23:51:40 2013
# Project:  pencil.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile pencil.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/phonon -I/usr/include/qt4 -Isrc -Isrc/external/linux -Isrc/external/macosx -Isrc/external/win32 -Isrc/interface -Isrc/graphics/bitmap -Isrc/graphics/vector -Isrc/structure -I/usr/include/qt4/phonon_compat -I/usr/X11R6/include -Irelease/build
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -lphonon -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = release/build/

####### Files

SOURCES       = src/graphics/bitmap/bitmapimage.cpp \
		src/graphics/bitmap/blur.cpp \
		src/graphics/vector/bezierarea.cpp \
		src/graphics/vector/beziercurve.cpp \
		src/graphics/vector/colourref.cpp \
		src/graphics/vector/gradient.cpp \
		src/graphics/vector/vectorimage.cpp \
		src/graphics/vector/vertexref.cpp \
		src/interface/editor.cpp \
		src/interface/mainwindow.cpp \
		src/interface/palette.cpp \
		src/interface/preferences.cpp \
		src/interface/scribblearea.cpp \
		src/interface/timecontrols.cpp \
		src/interface/timeline.cpp \
		src/interface/toolset.cpp \
		src/structure/layer.cpp \
		src/structure/layerimage.cpp \
		src/structure/layerbitmap.cpp \
		src/structure/layervector.cpp \
		src/structure/layercamera.cpp \
		src/structure/layersound.cpp \
		src/structure/object.cpp \
		src/main.cpp release/build/moc_editor.cpp \
		release/build/moc_mainwindow.cpp \
		release/build/moc_palette.cpp \
		release/build/moc_preferences.cpp \
		release/build/moc_scribblearea.cpp \
		release/build/moc_timecontrols.cpp \
		release/build/moc_timeline.cpp \
		release/build/moc_toolset.cpp \
		release/build/moc_layer.cpp \
		release/build/moc_layerbitmap.cpp \
		release/build/moc_layercamera.cpp \
		release/build/moc_layerimage.cpp \
		release/build/moc_layervector.cpp \
		release/build/moc_layersound.cpp \
		release/build/moc_object.cpp \
		release/build/qrc_pencil.cpp
OBJECTS       = release/build/bitmapimage.o \
		release/build/blur.o \
		release/build/bezierarea.o \
		release/build/beziercurve.o \
		release/build/colourref.o \
		release/build/gradient.o \
		release/build/vectorimage.o \
		release/build/vertexref.o \
		release/build/editor.o \
		release/build/mainwindow.o \
		release/build/palette.o \
		release/build/preferences.o \
		release/build/scribblearea.o \
		release/build/timecontrols.o \
		release/build/timeline.o \
		release/build/toolset.o \
		release/build/layer.o \
		release/build/layerimage.o \
		release/build/layerbitmap.o \
		release/build/layervector.o \
		release/build/layercamera.o \
		release/build/layersound.o \
		release/build/object.o \
		release/build/main.o \
		release/build/moc_editor.o \
		release/build/moc_mainwindow.o \
		release/build/moc_palette.o \
		release/build/moc_preferences.o \
		release/build/moc_scribblearea.o \
		release/build/moc_timecontrols.o \
		release/build/moc_timeline.o \
		release/build/moc_toolset.o \
		release/build/moc_layer.o \
		release/build/moc_layerbitmap.o \
		release/build/moc_layercamera.o \
		release/build/moc_layerimage.o \
		release/build/moc_layervector.o \
		release/build/moc_layersound.o \
		release/build/moc_object.o \
		release/build/qrc_pencil.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		pencil.pro
QMAKE_TARGET  = Pencil
DESTDIR       = release/
TARGET        = release/Pencil

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) release/ || $(MKDIR) release/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pencil.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile pencil.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile pencil.pro

dist: 
	@$(CHK_DIR_EXISTS) release/build/Pencil1.0.0 || $(MKDIR) release/build/Pencil1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) release/build/Pencil1.0.0/ && $(COPY_FILE) --parents src/graphics/vector/bezierarea.h src/graphics/vector/gradient.h src/interfaces.h src/interface/editor.h src/interface/mainwindow.h src/interface/palette.h src/interface/preferences.h src/interface/scribblearea.h src/interface/timecontrols.h src/interface/timeline.h src/interface/toolset.h src/structure/layer.h src/structure/layerbitmap.h src/structure/layercamera.h src/structure/layerimage.h src/structure/layervector.h src/structure/layersound.h src/structure/object.h release/build/Pencil1.0.0/ && $(COPY_FILE) --parents pencil.qrc release/build/Pencil1.0.0/ && $(COPY_FILE) --parents src/graphics/bitmap/bitmapimage.cpp src/graphics/bitmap/blur.cpp src/graphics/vector/bezierarea.cpp src/graphics/vector/beziercurve.cpp src/graphics/vector/colourref.cpp src/graphics/vector/gradient.cpp src/graphics/vector/vectorimage.cpp src/graphics/vector/vertexref.cpp src/interface/editor.cpp src/interface/mainwindow.cpp src/interface/palette.cpp src/interface/preferences.cpp src/interface/scribblearea.cpp src/interface/timecontrols.cpp src/interface/timeline.cpp src/interface/toolset.cpp src/structure/layer.cpp src/structure/layerimage.cpp src/structure/layerbitmap.cpp src/structure/layervector.cpp src/structure/layercamera.cpp src/structure/layersound.cpp src/structure/object.cpp src/main.cpp release/build/Pencil1.0.0/ && (cd `dirname release/build/Pencil1.0.0` && $(TAR) Pencil1.0.0.tar Pencil1.0.0 && $(COMPRESS) Pencil1.0.0.tar) && $(MOVE) `dirname release/build/Pencil1.0.0`/Pencil1.0.0.tar.gz . && $(DEL_FILE) -r release/build/Pencil1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: release/build/moc_editor.cpp release/build/moc_mainwindow.cpp release/build/moc_palette.cpp release/build/moc_preferences.cpp release/build/moc_scribblearea.cpp release/build/moc_timecontrols.cpp release/build/moc_timeline.cpp release/build/moc_toolset.cpp release/build/moc_layer.cpp release/build/moc_layerbitmap.cpp release/build/moc_layercamera.cpp release/build/moc_layerimage.cpp release/build/moc_layervector.cpp release/build/moc_layersound.cpp release/build/moc_object.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) release/build/moc_editor.cpp release/build/moc_mainwindow.cpp release/build/moc_palette.cpp release/build/moc_preferences.cpp release/build/moc_scribblearea.cpp release/build/moc_timecontrols.cpp release/build/moc_timeline.cpp release/build/moc_toolset.cpp release/build/moc_layer.cpp release/build/moc_layerbitmap.cpp release/build/moc_layercamera.cpp release/build/moc_layerimage.cpp release/build/moc_layervector.cpp release/build/moc_layersound.cpp release/build/moc_object.cpp
release/build/moc_editor.cpp: src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/scribblearea.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/graphics/vector/colourref.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interfaces.h \
		src/interface/editor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/editor.h -o release/build/moc_editor.cpp

release/build/moc_mainwindow.cpp: src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/scribblearea.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/graphics/vector/colourref.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interfaces.h \
		src/interface/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/mainwindow.h -o release/build/moc_mainwindow.cpp

release/build/moc_palette.cpp: src/interface/toolset.h \
		src/interface/palette.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/palette.h -o release/build/moc_palette.cpp

release/build/moc_preferences.cpp: src/interface/preferences.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/preferences.h -o release/build/moc_preferences.cpp

release/build/moc_scribblearea.cpp: src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/graphics/vector/colourref.h \
		src/interface/scribblearea.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/scribblearea.h -o release/build/moc_scribblearea.cpp

release/build/moc_timecontrols.cpp: src/interface/timecontrols.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/timecontrols.h -o release/build/moc_timecontrols.cpp

release/build/moc_timeline.cpp: src/interface/toolset.h \
		src/interface/timeline.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/timeline.h -o release/build/moc_timeline.cpp

release/build/moc_toolset.cpp: src/interface/toolset.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/interface/toolset.h -o release/build/moc_toolset.cpp

release/build/moc_layer.cpp: src/structure/layer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layer.h -o release/build/moc_layer.cpp

release/build/moc_layerbitmap.cpp: src/structure/layerimage.h \
		src/structure/layer.h \
		src/graphics/bitmap/bitmapimage.h \
		src/structure/layerbitmap.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layerbitmap.h -o release/build/moc_layerbitmap.cpp

release/build/moc_layercamera.cpp: src/structure/layerimage.h \
		src/structure/layer.h \
		src/graphics/bitmap/bitmapimage.h \
		src/structure/layercamera.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layercamera.h -o release/build/moc_layercamera.cpp

release/build/moc_layerimage.cpp: src/structure/layer.h \
		src/structure/layerimage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layerimage.h -o release/build/moc_layerimage.cpp

release/build/moc_layervector.cpp: src/structure/layerimage.h \
		src/structure/layer.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/structure/layervector.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layervector.h -o release/build/moc_layervector.cpp

release/build/moc_layersound.cpp: src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/layersound.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/layersound.h -o release/build/moc_layersound.cpp

release/build/moc_object.cpp: src/structure/layer.h \
		src/structure/layerbitmap.h \
		src/structure/layerimage.h \
		src/graphics/bitmap/bitmapimage.h \
		src/structure/layervector.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/vector/colourref.h \
		src/structure/object.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/structure/object.h -o release/build/moc_object.cpp

compiler_rcc_make_all: release/build/qrc_pencil.cpp
compiler_rcc_clean:
	-$(DEL_FILE) release/build/qrc_pencil.cpp
release/build/qrc_pencil.cpp: pencil.qrc \
		background/weave.jpg \
		background/dots.png \
		icons/select.png \
		icons/pen.png \
		icons/brush.png \
		icons/bucketTool.png \
		icons/add.png \
		icons/polyline.png \
		icons/arrow.png \
		icons/logo.png \
		icons/layer-sound.png \
		icons/eraser2.png \
		icons/move.png \
		icons/prefs-files.png \
		icons/icon.png \
		icons/prefstimeline.png \
		icons/aqua.png \
		icons/eyedropper.png \
		icons/smudge.png \
		icons/layer-vector.png \
		icons/magnify.png \
		icons/pencil2.png \
		icons/onionNext.png \
		icons/thinlines5.png \
		icons/layer-bitmap.png \
		icons/onionPrev.png \
		icons/house.png \
		icons/hand.png \
		icons/bucket.png \
		icons/prefspencil.png \
		icons/clear.png \
		icons/mirror.png \
		icons/layer-camera.png \
		icons/eraser.png \
		icons/outlines5.png \
		icons/remove.png \
		icons/controls/separator.png \
		icons/controls/play.png \
		icons/controls/sound.png \
		icons/controls/loop.png
	/usr/bin/rcc -name pencil pencil.qrc -o release/build/qrc_pencil.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

release/build/bitmapimage.o: src/graphics/bitmap/bitmapimage.cpp src/graphics/bitmap/bitmapimage.h \
		src/graphics/bitmap/blur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/bitmapimage.o src/graphics/bitmap/bitmapimage.cpp

release/build/blur.o: src/graphics/bitmap/blur.cpp src/graphics/bitmap/blur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/blur.o src/graphics/bitmap/blur.cpp

release/build/bezierarea.o: src/graphics/vector/bezierarea.cpp src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/bezierarea.o src/graphics/vector/bezierarea.cpp

release/build/beziercurve.o: src/graphics/vector/beziercurve.cpp src/graphics/vector/beziercurve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/beziercurve.o src/graphics/vector/beziercurve.cpp

release/build/colourref.o: src/graphics/vector/colourref.cpp src/graphics/vector/colourref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/colourref.o src/graphics/vector/colourref.cpp

release/build/gradient.o: src/graphics/vector/gradient.cpp src/graphics/vector/gradient.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/gradient.o src/graphics/vector/gradient.cpp

release/build/vectorimage.o: src/graphics/vector/vectorimage.cpp src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/vector/gradient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/vectorimage.o src/graphics/vector/vectorimage.cpp

release/build/vertexref.o: src/graphics/vector/vertexref.cpp src/graphics/vector/vertexref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/vertexref.o src/graphics/vector/vertexref.cpp

release/build/editor.o: src/interface/editor.cpp src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/scribblearea.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/graphics/vector/colourref.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interfaces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/editor.o src/interface/editor.cpp

release/build/mainwindow.o: src/interface/mainwindow.cpp src/interface/mainwindow.h \
		src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/scribblearea.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/graphics/vector/colourref.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interfaces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/mainwindow.o src/interface/mainwindow.cpp

release/build/palette.o: src/interface/palette.cpp src/interface/palette.h \
		src/interface/toolset.h \
		src/graphics/vector/colourref.h \
		src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/scribblearea.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/interface/preferences.h \
		src/interfaces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/palette.o src/interface/palette.cpp

release/build/preferences.o: src/interface/preferences.cpp src/interface/preferences.h \
		src/interface/scribblearea.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/graphics/vector/colourref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/preferences.o src/interface/preferences.cpp

release/build/scribblearea.o: src/interface/scribblearea.cpp src/interface/scribblearea.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/graphics/vector/colourref.h \
		src/interface/editor.h \
		src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interfaces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/scribblearea.o src/interface/scribblearea.cpp

release/build/timecontrols.o: src/interface/timecontrols.cpp src/interface/timecontrols.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/timecontrols.o src/interface/timecontrols.cpp

release/build/timeline.o: src/interface/timeline.cpp src/interface/timeline.h \
		src/interface/toolset.h \
		src/interface/editor.h \
		src/interface/scribblearea.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/bitmap/bitmapimage.h \
		src/graphics/vector/colourref.h \
		src/interface/preferences.h \
		src/interface/palette.h \
		src/interfaces.h \
		src/interface/timecontrols.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/timeline.o src/interface/timeline.cpp

release/build/toolset.o: src/interface/toolset.cpp src/interface/toolset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/toolset.o src/interface/toolset.cpp

release/build/layer.o: src/structure/layer.cpp src/structure/layer.h \
		src/structure/object.h \
		src/structure/layerbitmap.h \
		src/structure/layerimage.h \
		src/graphics/bitmap/bitmapimage.h \
		src/structure/layervector.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/vector/colourref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/layer.o src/structure/layer.cpp

release/build/layerimage.o: src/structure/layerimage.cpp src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/object.h \
		src/structure/layerbitmap.h \
		src/graphics/bitmap/bitmapimage.h \
		src/structure/layervector.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/vector/colourref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/layerimage.o src/structure/layerimage.cpp

release/build/layerbitmap.o: src/structure/layerbitmap.cpp src/structure/layerbitmap.h \
		src/structure/layerimage.h \
		src/structure/layer.h \
		src/graphics/bitmap/bitmapimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/layerbitmap.o src/structure/layerbitmap.cpp

release/build/layervector.o: src/structure/layervector.cpp src/structure/layervector.h \
		src/structure/layerimage.h \
		src/structure/layer.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/layervector.o src/structure/layervector.cpp

release/build/layercamera.o: src/structure/layercamera.cpp src/structure/layercamera.h \
		src/structure/layerimage.h \
		src/structure/layer.h \
		src/graphics/bitmap/bitmapimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/layercamera.o src/structure/layercamera.cpp

release/build/layersound.o: src/structure/layersound.cpp src/structure/layersound.h \
		src/structure/layerimage.h \
		src/structure/layer.h \
		src/structure/object.h \
		src/structure/layerbitmap.h \
		src/graphics/bitmap/bitmapimage.h \
		src/structure/layervector.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/vector/colourref.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/layersound.o src/structure/layersound.cpp

release/build/object.o: src/structure/object.cpp src/structure/object.h \
		src/structure/layer.h \
		src/structure/layerbitmap.h \
		src/structure/layerimage.h \
		src/graphics/bitmap/bitmapimage.h \
		src/structure/layervector.h \
		src/graphics/vector/vectorimage.h \
		src/graphics/vector/bezierarea.h \
		src/graphics/vector/vertexref.h \
		src/graphics/vector/beziercurve.h \
		src/graphics/vector/colourref.h \
		src/structure/layersound.h \
		src/structure/layercamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/object.o src/structure/object.cpp

release/build/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/main.o src/main.cpp

release/build/moc_editor.o: release/build/moc_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_editor.o release/build/moc_editor.cpp

release/build/moc_mainwindow.o: release/build/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_mainwindow.o release/build/moc_mainwindow.cpp

release/build/moc_palette.o: release/build/moc_palette.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_palette.o release/build/moc_palette.cpp

release/build/moc_preferences.o: release/build/moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_preferences.o release/build/moc_preferences.cpp

release/build/moc_scribblearea.o: release/build/moc_scribblearea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_scribblearea.o release/build/moc_scribblearea.cpp

release/build/moc_timecontrols.o: release/build/moc_timecontrols.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_timecontrols.o release/build/moc_timecontrols.cpp

release/build/moc_timeline.o: release/build/moc_timeline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_timeline.o release/build/moc_timeline.cpp

release/build/moc_toolset.o: release/build/moc_toolset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_toolset.o release/build/moc_toolset.cpp

release/build/moc_layer.o: release/build/moc_layer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_layer.o release/build/moc_layer.cpp

release/build/moc_layerbitmap.o: release/build/moc_layerbitmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_layerbitmap.o release/build/moc_layerbitmap.cpp

release/build/moc_layercamera.o: release/build/moc_layercamera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_layercamera.o release/build/moc_layercamera.cpp

release/build/moc_layerimage.o: release/build/moc_layerimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_layerimage.o release/build/moc_layerimage.cpp

release/build/moc_layervector.o: release/build/moc_layervector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_layervector.o release/build/moc_layervector.cpp

release/build/moc_layersound.o: release/build/moc_layersound.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_layersound.o release/build/moc_layersound.cpp

release/build/moc_object.o: release/build/moc_object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/moc_object.o release/build/moc_object.cpp

release/build/qrc_pencil.o: release/build/qrc_pencil.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/build/qrc_pencil.o release/build/qrc_pencil.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

